version: '3.3'

volumes:
    static_value:
    media_value:
    
services:
  
  backend:

    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/code/static_backend/
      - media_value:/code/media_backend/
    
    

