# Generated by Django 3.2.6 on 2022-02-21 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_character_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 16, 58, 18, 557354, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
