# Generated by Django 3.2.6 on 2022-02-21 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_character_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 21, 17, 0, 6, 633646, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
