# Generated by Django 3.2.6 on 2022-02-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_character_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
