# Generated by Django 3.2.6 on 2022-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_character_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения, mm/dd/gg'),
        ),
    ]
