# Generated by Django 3.2.6 on 2022-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_character_charisma_ability_modifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='floor',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
    ]
