# Generated by Django 3.2.6 on 2022-03-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220324_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.TextField(blank=True),
        ),
    ]
