# Generated by Django 3.2.6 on 2022-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_character_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='floor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.TextField(blank=True),
        ),
    ]
