# Generated by Django 3.2.6 on 2022-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220324_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.TextField(blank=True),
        ),
    ]
