# Generated by Django 3.2.6 on 2022-03-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_character_worldview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='worldview',
            field=models.TextField(blank=True),
        ),
    ]
