# Generated by Django 3.2.6 on 2022-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20220324_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hit_points_damage_reduction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points_nonlethal_damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points_wounds_current_HP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
