# Generated by Django 3.2.6 on 2022-03-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20220324_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points_wounds_current_HP',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
