# Generated by Django 3.2.6 on 2022-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20220328_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
