# Generated by Django 3.1.7 on 2022-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20220328_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
    ]
