# Generated by Django 3.2.6 on 2022-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20220404_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='worldview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
