# Generated by Django 3.2.6 on 2022-04-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20220329_1701'),
        ('blog', '0028_auto_20220404_1941'),
    ]

    operations = [
    ]
