# Generated by Django 3.2.6 on 2022-04-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20220421_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='circumstance_modifier_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='circumstance_modifier_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='languachies_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='languachies_three',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='languachies_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_craft_one_dop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_craft_three_dop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_craft_two_dop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_religion_attribute_modifiers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_religion_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_religion_misc_mod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_religion_points_skill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_religion_total_bonus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
