# Generated by Django 3.2.6 on 2022-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20220429_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
