# Generated by Django 3.2.6 on 2022-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20220512_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equipment_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
