# Generated by Django 3.2.6 on 2022-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_character_equipment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='get_off_the_ground',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='hight_load',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='raise_above_head',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
